# Generated by Django 5.1.1 on 2024-11-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_path", models.TextField(blank=True, null=True)),
                ("event_type", models.TextField(blank=True, null=True)),
                ("object_type", models.TextField(blank=True, null=True)),
                ("object_id", models.BigIntegerField(blank=True, null=True)),
                ("object_uuid", models.TextField(blank=True, null=True)),
                ("data", models.JSONField()),
                ("event_tone", models.TextField(blank=True, default="neutral")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.TextField(blank=True, default="anonymous")),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "event_path",
                            "event_type",
                            "object_type",
                            "object_id",
                            "account",
                            "created_at",
                            "event_tone",
                        ],
                        name="Analytics_e_event_p_80bf0a_idx",
                    )
                ],
            },
        ),
    ]
