# Generated by Django 5.1.1 on 2024-12-11 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.TextField()),
                ("country", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("city_metadata", models.JSONField(blank=True, null=True)),
                ("country_metadata", models.JSONField(blank=True, null=True)),
                (
                    "is_mobile",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_tablet",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_touch_capable",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("is_pc", models.BooleanField(blank=True, default=False, null=True)),
                ("is_bot", models.BooleanField(blank=True, default=False, null=True)),
                ("browser", models.TextField(blank=True, null=True)),
                ("browser_version", models.TextField(blank=True, null=True)),
                ("os", models.TextField(blank=True, null=True)),
                ("os_version", models.TextField(blank=True, null=True)),
                ("device", models.TextField(blank=True, null=True)),
                ("account", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "ip",
                            "created_at",
                            "country",
                            "city",
                            "country_metadata",
                            "city_metadata",
                            "account",
                            "browser",
                            "browser_version",
                            "is_pc",
                            "is_mobile",
                            "is_tablet",
                            "is_bot",
                            "is_touch_capable",
                            "device",
                            "os_version",
                            "os",
                        ],
                        name="Analytics_d_ip_8ce667_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UsersActivityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("hash", models.TextField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["data", "hash", "created_at"],
                        name="Analytics_u_data_f67dcc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_path", models.TextField(blank=True, null=True)),
                ("event_type", models.TextField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.TextField(blank=True, default="anonymous", null=True),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Analytics.device",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "event_path",
                            "event_type",
                            "account",
                            "created_at",
                            "device",
                        ],
                        name="Analytics_e_event_p_4edbd0_idx",
                    )
                ],
            },
        ),
    ]
