# Generated by Django 5.1.1 on 2024-12-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=[
                    "ip",
                    "created_at",
                    "country",
                    "city",
                    "country_metadata",
                    "city_metadata",
                    "account",
                    "browser",
                    "browser_version",
                    "is_pc",
                    "is_mobile",
                    "is_tablet",
                    "is_bot",
                    "is_touch_capable",
                    "device",
                    "os_version",
                    "os",
                ],
                name="Analytics_d_ip_8ce667_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_path", "event_type", "account", "created_at", "device"],
                name="Analytics_e_event_p_4edbd0_idx",
            ),
        ),
    ]
