# Generated by Django 5.1.1 on 2024-11-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="data",
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
