# Generated by Django 5.1.1 on 2024-12-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0002_device_analytics_d_ip_8ce667_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsersActivityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("hash", models.TextField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["data", "hash", "created_at"],
                        name="Analytics_u_data_f67dcc_idx",
                    )
                ],
            },
        ),
    ]
