# Generated by Django 5.1.1 on 2024-11-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0002_alter_event_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
