# Generated by Django 5.1.1 on 2024-11-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0003_alter_event_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_tone",
            field=models.TextField(blank=True, default="neutral", null=True),
        ),
    ]
