# Generated by Django 5.1.1 on 2024-11-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0004_alter_event_event_tone"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="Analytics_e_event_p_80bf0a_idx",
        ),
        migrations.RemoveField(
            model_name="event",
            name="event_tone",
        ),
        migrations.RemoveField(
            model_name="event",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="object_type",
        ),
        migrations.RemoveField(
            model_name="event",
            name="object_uuid",
        ),
        migrations.AlterField(
            model_name="event",
            name="account",
            field=models.TextField(blank=True, default="anonymous", null=True),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_path", "event_type", "account", "created_at"],
                name="Analytics_e_event_p_01647a_idx",
            ),
        ),
    ]
