# Generated by Django 5.1.1 on 2024-12-09 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0005_remove_event_analytics_e_event_p_80bf0a_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("email", models.TextField()),
                ("addresses", models.JSONField(default=[])),
                ("userAgents", models.JSONField(default=[])),
                ("locations", models.JSONField(default=[])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="Analytics_e_event_p_01647a_idx",
        ),
        migrations.AddIndex(
            model_name="fingerprint",
            index=models.Index(
                fields=["username", "email", "created_at", "updated_at"],
                name="Analytics_f_usernam_f923ff_idx",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="fingerprint",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Analytics.fingerprint",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=[
                    "event_path",
                    "event_type",
                    "account",
                    "created_at",
                    "fingerprint",
                ],
                name="Analytics_e_event_p_777966_idx",
            ),
        ),
        migrations.AddField(
            model_name="tribe",
            name="members",
            field=models.ManyToManyField(
                related_name="members", to="Analytics.fingerprint"
            ),
        ),
        migrations.AddIndex(
            model_name="tribe",
            index=models.Index(
                fields=["created_at", "updated_at"],
                name="Analytics_t_created_fdf724_idx",
            ),
        ),
    ]
