# Generated by Django 5.1.1 on 2025-01-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmimage",
            name="image",
            field=models.ImageField(
                upload_to="images/dm/fe7f178b215e46d87b73a7795e0aaf37b68f85ddc77a2f90262a862cce776d97/"
            ),
        ),
        migrations.AlterField(
            model_name="dmvoicenote",
            name="voiceNote",
            field=models.FileField(
                upload_to="voiceNotes/dm/4192fec2dff693236b1e76f2de7dab572264111480a6ee3560cda442a1f1ad37/"
            ),
        ),
    ]
