# Generated by Django 5.1.1 on 2025-05-16 14:01

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="writeup",
            name="voidbackApi_author__315fc0_idx",
        ),
        migrations.RemoveField(
            model_name="writeup",
            name="rank",
        ),
        migrations.AlterField(
            model_name="writeupthumbnail",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=False,
                quality=100,
                scale=1,
                size=[1600, 900],
                upload_to="thumbnails/",
            ),
        ),
        migrations.AddIndex(
            model_name="writeup",
            index=models.Index(
                fields=[
                    "author",
                    "title",
                    "series",
                    "edited",
                    "created_at",
                    "updated_at",
                ],
                name="voidbackApi_author__50a0fa_idx",
            ),
        ),
    ]
