# Generated by Django 5.1.1 on 2025-01-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmimage",
            name="image",
            field=models.ImageField(
                upload_to="images/dm/98eb0dcb5d6bc44cafd624576d9ebf902d5b9a00e4d061a8fe100414a44dd802/"
            ),
        ),
        migrations.AlterField(
            model_name="dmvoicenote",
            name="voiceNote",
            field=models.FileField(
                upload_to="voiceNotes/dm/a63ffcc418d513538fc681c49a1ad0602c65e9d8445e9e13c3c450dd130dbec1/"
            ),
        ),
        migrations.AlterField(
            model_name="postmetadata",
            name="text_sentiment",
            field=models.TextField(),
        ),
    ]
