# Generated by Django 5.1.1 on 2025-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="from_mobile",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
