# Generated by Django 5.1.1 on 2025-01-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0002_alter_dmimage_image_alter_dmvoicenote_voicenote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmimage",
            name="image",
            field=models.ImageField(
                upload_to="images/dm/a2b449d732d61b07e7ea60ad7881154ed7b0b93ccbb71c09da2d3312f6f63dde/"
            ),
        ),
        migrations.AlterField(
            model_name="dmvoicenote",
            name="voiceNote",
            field=models.FileField(
                upload_to="voiceNotes/dm/0a8a56be15d3ebc79c18b993b6d754dabfe27c417e7d354e932c7c48b2852b8d/"
            ),
        ),
    ]
