# Generated by Django 5.1.1 on 2024-11-25 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0002_account_ban_exp_account_is_banned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resolved_by",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
