# Generated by Django 5.1.1 on 2025-01-15 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voidbackApi",
            "0002_alter_dmimage_image_alter_dmvoicenote_voicenote_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessagesession",
            name="archived_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="archived_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dmimage",
            name="image",
            field=models.ImageField(
                upload_to="images/dm/2772bd8a40107dbdf3c51691f6c84042a036d44ad4678e3d5bd57c442ffdcc3a/"
            ),
        ),
        migrations.AlterField(
            model_name="dmvoicenote",
            name="voiceNote",
            field=models.FileField(
                upload_to="voiceNotes/dm/fb38dcfbc89707e870d1924d98a6f5dc63aaf106cc43c724decc0c7478ff86e0/"
            ),
        ),
    ]
