# Generated by Django 5.1.1 on 2025-01-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0003_alter_dmimage_image_alter_dmvoicenote_voicenote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmimage",
            name="image",
            field=models.ImageField(upload_to="images/dm/"),
        ),
        migrations.AlterField(
            model_name="dmvoicenote",
            name="voiceNote",
            field=models.FileField(upload_to="voiceNotes/dm/"),
        ),
    ]
