# Generated by Django 5.1.1 on 2025-01-15 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0003_alter_directmessagesession_archived_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessagesession",
            name="archived_by",
            field=models.ManyToManyField(
                blank=True, related_name="archived_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="dmimage",
            name="image",
            field=models.ImageField(
                upload_to="images/dm/8e9cd857c573a9c6eca4094424da01b9dc6cc7688f00e61576e726683c11dfd7/"
            ),
        ),
        migrations.AlterField(
            model_name="dmvoicenote",
            name="voiceNote",
            field=models.FileField(
                upload_to="voiceNotes/dm/95552486ca56a0d3ca8b8e5e6c265b4832cbd35ae7610a5ff884afbe0c3d4547/"
            ),
        ),
    ]
