# Generated by Django 5.1.1 on 2025-02-19 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0003_dmimage_directmessagesession_dmmessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EdgeRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=30)),
                (
                    "description",
                    models.TextField(blank=True, max_length=2500, null=True),
                ),
                ("rank", models.BigIntegerField(blank=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoomCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.TextField(blank=True, max_length=60)),
                ("rank", models.BigIntegerField(blank=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="voidbackApi.edgeroom",
            ),
        ),
        migrations.CreateModel(
            name="EdgeRoomConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isPublic", models.BooleanField(blank=True, default=True)),
                ("default_member_permissions", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="edgeroom",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="voidbackApi.edgeroomconfig",
            ),
        ),
        migrations.CreateModel(
            name="MemberPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_moderator", models.BooleanField(blank=True, default=False)),
                (
                    "upated_reason",
                    models.TextField(blank=True, default="", max_length=3000),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("can_delete_posts", models.BooleanField(blank=True, default=False)),
                ("can_remove_members", models.BooleanField(blank=True, default=False)),
                (
                    "can_remove_moderators",
                    models.BooleanField(blank=True, default=False),
                ),
                ("can_add_moderators", models.BooleanField(blank=True, default=False)),
                ("can_post", models.BooleanField(blank=True, default=True)),
                ("can_like", models.BooleanField(blank=True, default=True)),
                ("can_dislike", models.BooleanField(blank=True, default=True)),
                ("can_reply", models.BooleanField(blank=True, default=True)),
                ("can_post_image", models.BooleanField(blank=True, default=False)),
                ("can_add_members", models.BooleanField(blank=True, default=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="edgeroom",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, to="voidbackApi.roomcategory"
            ),
        ),
        migrations.CreateModel(
            name="RoomMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.BigIntegerField(blank=True, default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permissions",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voidbackApi.memberpermissions",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voidbackApi.edgeroom",
                    ),
                ),
            ],
        ),
    ]
