# Generated by Django 5.1.1 on 2025-01-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0004_alter_directmessagesession_archived_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dmmessage",
            name="parent",
        ),
        migrations.AlterField(
            model_name="dmimage",
            name="image",
            field=models.ImageField(
                upload_to="images/dm/5cd9fb234965e72d88923ce7c1b4e5f324bef916b4bcefb7164545a082981c76/"
            ),
        ),
        migrations.AlterField(
            model_name="dmvoicenote",
            name="voiceNote",
            field=models.FileField(
                upload_to="voiceNotes/dm/f79df94c174c2bdd1be89893847f5dca76c0dccf9cf1e0322f1cff32b841dad8/"
            ),
        ),
    ]
