# Generated by Django 5.1.1 on 2024-11-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0004_alter_notification_navpath"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="email_verified",
        ),
    ]
