# Generated by Django 5.1.1 on 2025-02-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0004_edgeroom_roomcategory_post_room_edgeroomconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edgeroom",
            name="categories",
            field=models.ManyToManyField(blank=True, to="voidbackApi.roomcategory"),
        ),
    ]
