# Generated by Django 5.1.1 on 2025-01-19 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0005_remove_dmmessage_parent_alter_dmimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmimage",
            name="image",
            field=models.ImageField(
                upload_to="images/dm/3d84af52844f952c96fb50092f6f42ecf492260c73d5d9ad73c81b96b3f5c497/"
            ),
        ),
        migrations.AlterField(
            model_name="dmvoicenote",
            name="voiceNote",
            field=models.FileField(
                upload_to="voiceNotes/dm/87c290291d63cd5ad4222d52f82774453689bc35ffd663cbf1e27e939bfee97a/"
            ),
        ),
        migrations.CreateModel(
            name="AccountActiveStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isActive", models.BooleanField(default=False)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
