# Generated by Django 5.1.1 on 2024-12-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0005_remove_account_email_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="ban_exp",
        ),
        migrations.RemoveField(
            model_name="account",
            name="is_banned",
        ),
    ]
