# Generated by Django 5.1.1 on 2025-02-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0006_remove_foryou_voidbackapi_account_c33764_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datahubaccount",
            name="account",
        ),
        migrations.RemoveField(
            model_name="datahubfeedbackpoll",
            name="account",
        ),
        migrations.RemoveField(
            model_name="datahubquery",
            name="account",
        ),
        migrations.RemoveField(
            model_name="postmetadata",
            name="post",
        ),
        migrations.RemoveField(
            model_name="researchpaper",
            name="author",
        ),
        migrations.RemoveField(
            model_name="researchpaperimpression",
            name="paper",
        ),
        migrations.RemoveField(
            model_name="researchpaperimpression",
            name="account",
        ),
        migrations.DeleteModel(
            name="DataHubPositionPoll",
        ),
        migrations.DeleteModel(
            name="DataHubFeedbackPoll",
        ),
        migrations.DeleteModel(
            name="DataHubAccount",
        ),
        migrations.DeleteModel(
            name="DataHubQuery",
        ),
        migrations.DeleteModel(
            name="PostMetadata",
        ),
        migrations.DeleteModel(
            name="ResearchPaper",
        ),
        migrations.DeleteModel(
            name="ResearchPaperImpression",
        ),
    ]
