# Generated by Django 5.1.1 on 2025-01-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voidbackApi",
            "0006_alter_dmimage_image_alter_dmvoicenote_voicenote_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountactivestatus",
            name="isActive",
        ),
        migrations.AlterField(
            model_name="dmimage",
            name="image",
            field=models.ImageField(
                upload_to="images/dm/abcfcbb792e9237ca94303fb1e31addbded81e5f91a6fbefeb9986018c43d1ae/"
            ),
        ),
        migrations.AlterField(
            model_name="dmvoicenote",
            name="voiceNote",
            field=models.FileField(
                upload_to="voiceNotes/dm/b71ca35f4de766c849731a194b070a8d93014ab2065bf93b916abbd9eed19181/"
            ),
        ),
    ]
