# Generated by Django 5.1.1 on 2024-12-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0006_remove_account_ban_exp_remove_account_is_banned"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email_verified",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
