# Generated by Django 5.1.1 on 2024-12-07 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0007_account_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foryou",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="username",
                unique=True,
            ),
        ),
    ]
