# Generated by Django 5.1.1 on 2025-01-20 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0007_remove_accountactivestatus_isactive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmimage",
            name="image",
            field=models.ImageField(
                upload_to="images/dm/89db4da05e62348db4eec4039e3812270c902cd85228978e1d4e2484753dde4c/"
            ),
        ),
        migrations.AlterField(
            model_name="dmvoicenote",
            name="voiceNote",
            field=models.FileField(
                upload_to="voiceNotes/dm/ac57d2791d24f1e18211f8e6a04b8e75034c4dd182d357defc0b623999ac6135/"
            ),
        ),
        migrations.CreateModel(
            name="RealtimeSessionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sessionHash", models.TextField(unique=True)),
                (
                    "recording",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "typing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["typing", "recording", "sessionHash"],
                        name="voidbackApi_typing__e36f99_idx",
                    )
                ],
            },
        ),
    ]
