# Generated by Django 5.1.1 on 2025-03-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0008_alter_roomcategory_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memberpermissions",
            old_name="can_remove_members",
            new_name="can_remove_member",
        ),
    ]
