# Generated by Django 5.1.1 on 2024-12-07 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0008_alter_foryou_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataHubAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("queries_left", models.BigIntegerField(blank=True, default=10)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataHubQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_category", models.TextField(blank=True, default="symbol")),
                ("query_startDate", models.DateField()),
                ("query_endDate", models.DateField()),
                ("includes_symbols", models.JSONField()),
                ("includes_hashtags", models.JSONField()),
                ("includes_keywords", models.JSONField()),
                ("query_results", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voidbackApi.datahubaccount",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="datahubaccount",
            index=models.Index(
                fields=["account", "created_at", "queries_left"],
                name="voidbackApi_account_c9aad6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datahubquery",
            index=models.Index(
                fields=[
                    "account",
                    "created_at",
                    "query_category",
                    "query_startDate",
                    "query_endDate",
                    "includes_hashtags",
                    "includes_symbols",
                    "includes_keywords",
                    "query_results",
                ],
                name="voidbackApi_account_abb47e_idx",
            ),
        ),
    ]
