# Generated by Django 5.1.1 on 2025-01-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voidbackApi",
            "0008_alter_dmimage_image_alter_dmvoicenote_voicenote_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmimage",
            name="image",
            field=models.ImageField(
                upload_to="images/dm/7440c10e5fd7d97f1643f05ece272b91cf12b41af4ea2e19b3142cbf3775f8fe/"
            ),
        ),
        migrations.AlterField(
            model_name="dmvoicenote",
            name="voiceNote",
            field=models.FileField(
                upload_to="voiceNotes/dm/82d11db0e9823849bf97032ecb4fe8cf79bc46a935613137bf775fb68f2e3da4/"
            ),
        ),
        migrations.DeleteModel(
            name="RealtimeSessionStatus",
        ),
    ]
