# Generated by Django 5.1.1 on 2025-03-05 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "voidbackApi",
            "0009_rename_can_remove_members_memberpermissions_can_remove_member",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="memberpermissions",
            old_name="can_remove_member",
            new_name="can_remove_members",
        ),
    ]
