# Generated by Django 5.1.1 on 2024-12-07 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0009_datahubaccount_datahubquery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foryou",
            name="account",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
