# Generated by Django 5.1.1 on 2024-12-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0010_alter_foryou_account"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="datahubquery",
            name="voidbackApi_account_abb47e_idx",
        ),
        migrations.RemoveField(
            model_name="datahubquery",
            name="includes_hashtags",
        ),
        migrations.RemoveField(
            model_name="datahubquery",
            name="includes_symbols",
        ),
        migrations.AddField(
            model_name="datahubquery",
            name="query",
            field=models.TextField(default="none"),
        ),
        migrations.AddIndex(
            model_name="datahubquery",
            index=models.Index(
                fields=[
                    "account",
                    "query",
                    "created_at",
                    "query_category",
                    "query_startDate",
                    "query_endDate",
                    "includes_keywords",
                    "query_results",
                ],
                name="voidbackApi_account_e4dceb_idx",
            ),
        ),
    ]
