# Generated by Django 5.1.1 on 2025-03-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "voidbackApi",
            "0010_rename_can_remove_member_memberpermissions_can_remove_members",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="email_verified",
        ),
    ]
