# Generated by Django 5.1.1 on 2024-12-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voidbackApi",
            "0011_remove_datahubquery_voidbackapi_account_abb47e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="datahubquery",
            name="topPost",
            field=models.JSONField(null=True),
        ),
    ]
