# Generated by Django 5.1.1 on 2025-03-07 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0011_remove_account_email_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.TextField(blank=True, max_length=80)),
                ("rank", models.BigIntegerField(blank=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DatasetFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("file", models.FileField(upload_to="ml/datasets/")),
                ("file_type", models.CharField(blank=True, default="json")),
            ],
        ),
        migrations.CreateModel(
            name="DatasetThumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/thumbnails/")),
            ],
        ),
        migrations.RemoveField(
            model_name="edgeroomconfig",
            name="isPublic",
        ),
        migrations.AlterField(
            model_name="edgeroom",
            name="name",
            field=models.TextField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField()),
                ("total_size", models.BigIntegerField(default=0)),
                ("downloads", models.BigIntegerField(default=0)),
                ("models_trained", models.BigIntegerField(default=0)),
                ("credit_sources", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="categories", to="voidbackApi.datasetcategory"
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        related_name="files", to="voidbackApi.datasetfile"
                    ),
                ),
                (
                    "thumbnail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="voidbackApi.datasetthumbnail",
                    ),
                ),
            ],
        ),
    ]
