# Generated by Django 5.1.1 on 2024-12-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0012_datahubquery_toppost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datahubquery",
            name="topPost",
        ),
    ]
