# Generated by Django 5.1.1 on 2024-12-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0013_remove_datahubquery_toppost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datahubquery",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="voidbackApi.datahubaccount",
            ),
        ),
        migrations.CreateModel(
            name="DataHubFeedbackPoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.TextField()),
                ("position", models.IntegerField(default=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hash", models.TextField(unique=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="voidbackApi.datahubaccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["account", "ticker", "position", "created_at"],
                        name="voidbackApi_account_e5a25f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataHubPositionPoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.TextField()),
                ("position", models.IntegerField(default=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hash", models.TextField(unique=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="voidbackApi.datahubaccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["account", "ticker", "position", "created_at"],
                        name="voidbackApi_account_9b5ab0_idx",
                    )
                ],
            },
        ),
    ]
