# Generated by Django 5.1.1 on 2025-03-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0014_dataset_total_files_datasetfile_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetfile",
            name="hash",
            field=models.TextField(null=True, unique=True),
        ),
    ]
