# Generated by Django 5.1.1 on 2024-12-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0014_alter_datahubquery_account_datahubfeedbackpoll_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="from_mobile",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
