# Generated by Django 5.1.1 on 2025-01-10 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0015_post_from_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DMImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/dm/023573785d739b9ac5722874292c0df9701de9a56a0accb8ac12ea988c4a9636/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DMVoiceNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voiceNote",
                    models.FileField(
                        upload_to="voiceNotes/dm/259eabfe352657bfe3e644f08cd5104a66bdc8398d45196ce14359751f003969/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DirectMessageSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DMMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=5000)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("seen", models.BooleanField(blank=True, default=False)),
                ("seen_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voidbackApi.dmimage",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="voidbackApi.inboxmessage",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voidbackApi.post",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="voidbackApi.directmessagesession",
                    ),
                ),
                (
                    "voiceNote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voidbackApi.dmvoicenote",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="directmessagesession",
            index=models.Index(
                fields=["initiator", "friend", "created_at"],
                name="voidbackApi_initiat_295f77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dmmessage",
            index=models.Index(
                fields=["session", "sender", "seen", "seen_at", "sent_at"],
                name="voidbackApi_session_5da0fd_idx",
            ),
        ),
    ]
