# Generated by Django 5.1.1 on 2025-03-25 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0019_series_tag_writeup_writeupimpression_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
