# Generated by Django 5.1.1 on 2025-03-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0020_series_author"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="foryou",
            name="voidbackApi_account_b559aa_idx",
        ),
        migrations.RemoveField(
            model_name="foryou",
            name="rooms",
        ),
        migrations.AlterField(
            model_name="foryou",
            name="authors",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="foryou",
            name="series",
            field=models.JSONField(default={}),
        ),
        migrations.AddIndex(
            model_name="foryou",
            index=models.Index(
                fields=[
                    "account",
                    "series",
                    "tags",
                    "authors",
                    "created_at",
                    "updated_at",
                ],
                name="voidbackApi_account_6d54d2_idx",
            ),
        ),
    ]
