# Generated by Django 5.1.1 on 2025-03-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0021_remove_foryou_voidbackapi_account_b559aa_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foryou",
            name="authors",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="foryou",
            name="series",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="foryou",
            name="tags",
            field=models.JSONField(default=[]),
        ),
    ]
