# Generated by Django 5.1.1 on 2025-03-30 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0022_alter_foryou_authors_alter_foryou_series_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_parent",
                        to="voidbackApi.comment",
                    ),
                ),
                (
                    "writeup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voidbackApi.writeup",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["comment", "writeup", "author", "created_at"],
                        name="voidbackApi_comment_798dd1_idx",
                    )
                ],
            },
        ),
    ]
