# Generated by Django 5.1.1 on 2025-03-31 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0024_alter_comment_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impression", models.IntegerField(blank=True, default=1)),
                ("hash", models.TextField(blank=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_impression",
                        to="voidbackApi.comment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "comment",
                            "account",
                            "impression",
                            "hash",
                            "created_at",
                            "updated_at",
                        ],
                        name="voidbackApi_comment_429c85_idx",
                    )
                ],
            },
        ),
    ]
