# Generated by Django 5.1.1 on 2025-04-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0025_commentimpression"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="writeup",
            name="voidbackApi_author__9a5a98_idx",
        ),
        migrations.AddField(
            model_name="writeup",
            name="edited",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddIndex(
            model_name="writeup",
            index=models.Index(
                fields=[
                    "author",
                    "title",
                    "series",
                    "edited",
                    "rank",
                    "created_at",
                    "updated_at",
                ],
                name="voidbackApi_author__315fc0_idx",
            ),
        ),
    ]
