# Generated by Django 5.1.1 on 2025-04-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0027_remove_comment_voidbackapi_comment_798dd1_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchquery",
            name="object_name",
            field=models.TextField(default=""),
        ),
    ]
