# Generated by Django 5.1.1 on 2025-04-05 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0028_alter_searchquery_object_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writeup",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="voidbackApi.series",
            ),
        ),
    ]
