# Generated by Django 5.1.1 on 2025-04-05 11:31

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0029_alter_writeup_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writeupthumbnail",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="PNG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[350, 250],
                upload_to="thumbnails/",
            ),
        ),
    ]
