# Generated by Django 5.1.1 on 2025-04-05 11:56

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0032_alter_account_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="avatar",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=False,
                null=True,
                quality=100,
                scale=1,
                size=[320, 320],
                upload_to="avatars/",
            ),
        ),
        migrations.AlterField(
            model_name="writeupthumbnail",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=False,
                quality=100,
                scale=1,
                size=[350, 250],
                upload_to="thumbnails/",
            ),
        ),
    ]
