# Generated by Django 5.1.1 on 2025-04-05 12:29

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voidbackApi", "0033_alter_account_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writeupthumbnail",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=False,
                quality=100,
                scale=1,
                size=[300, 300],
                upload_to="thumbnails/",
            ),
        ),
    ]
