# Generated by Django 5.1.1 on 2024-11-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greedyFetch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachedresponse",
            name="headers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cachedresponse",
            name="body",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
