# Generated by Django 5.1.1 on 2024-11-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greedyFetch", "0002_cachedresponse_headers_alter_cachedresponse_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedresponse",
            name="body",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="cachedresponse",
            name="headers",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
