# Generated by Django 5.1.1 on 2024-11-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greedyFetch", "0004_alter_cachedresponse_body_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CachedResponse",
        ),
    ]
